---
iosv-1:
    hostname: '192.168.152.11'
    port: 22
    username: 'cisco'
    password: 'cisco'
    platform: 'cisco_ios'

iosv-2:
    hostname: '192.168.152.12'
    port: 22
    username: 'cisco'
    password: 'cisco'
    platform: 'cisco_ios'

