---
- name: Enable LLDP
  hosts: "devices"
  gather_facts: false
  connection: network_cli


  tasks:
    - name: enable LLDP service
      ios_lldp:
        state: present

      register: output

    - name: show output
      debug:
        var: output

