---
- name: Ansible Group and Host Varibles
  hosts: localhost

  tasks:
    - name: create router configuration files
      template: 
        src=/home/echou/Mastering_Python_Networking_third_edition/Chapter05/Includes/nxos.j2
        dest=/home/echou/Mastering_Python_Networking_third_edition/Chapter05/Includes/{{ item.key }}.conf
      with_dict: "{{ nexus_devices }}"
      register: output

    - include: show_output.yml
